FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build

# build application 
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/core/sdk:2.1

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "location_service.dll"]