version: "3"
services:
    basket-service:
        build: ./basket-service
        ports:
            - "5000:80"
            - "5001:80"
    basket-service-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1434:1433"
        environment:
            SA_PASSWORD: "Welcome1234.?"
            ACCEPT_EULA: "Y"
    catalog-service:
        build: ./catalog-service
        ports:
            - "5002:80"
            - "5003:80"
    identity-service:
        build: ./identity-service
        ports:
            - "5004:80"
            - "5005:80"
    location-service:
        build: ./location-service
        ports:
            - "5006:80"
            - "5007:80"
    marketing-service:
        build: ./marketing-service
        ports:
            - "5008:80"
            - "5009:80"
    ordering-service:
        build: ./ordering-service
        ports:
            - "5010:80"
            - "5011:80"