FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# build application 
WORKDIR /src
COPY . .
COPY .. .
RUN dotnet restore
RUN dotnet publish -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_brand_listener.dll"]