FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# build application 
WORKDIR /src
COPY . .
RUN dotnet restore api/catalog-service-api.fsproj

WORKDIR /src/api
RUN dotnet build catalog-service-api.fsproj

WORKDIR /src/api
RUN dotnet publish catalog-service-api.fsproj -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_service.dll"]