FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# build application 
WORKDIR /src
COPY . .
RUN dotnet restore api/catalog-service-api.fsproj

WORKDIR /src/api
RUN dotnet build catalog-service-api.fsproj  -c Release

WORKDIR /src/api
RUN dotnet publish catalog-service-api.fsproj -c Release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_service.dll"]