FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# build application 
WORKDIR /src
COPY . .
# final stage/image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_listener.dll"]