FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# build application 
WORKDIR /src
COPY . .
# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_listener.dll"]