FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# build application 
WORKDIR /src
COPY . .
RUN dotnet restore catalog-service-api.fsproj
RUN dotnet publish catalog-service-api.fsproj -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "catalog_service.dll"]