USE [master]
GO
/****** Object:  Database [Events]    Script Date: 27/08/2022 09:45:27 ******/
CREATE DATABASE [Events]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Events', FILENAME = N'/var/opt/mssql/data/Events.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Events_log', FILENAME = N'/var/opt/mssql/data/Events_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Events] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Events].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Events] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Events] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Events] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Events] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Events] SET ARITHABORT OFF 
GO
ALTER DATABASE [Events] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Events] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Events] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Events] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Events] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Events] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Events] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Events] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Events] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Events] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Events] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Events] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Events] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Events] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Events] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Events] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Events] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Events] SET RECOVERY FULL 
GO
ALTER DATABASE [Events] SET  MULTI_USER 
GO
ALTER DATABASE [Events] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Events] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Events] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Events] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Events] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Events] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Events', N'ON'
GO
ALTER DATABASE [Events] SET QUERY_STORE = OFF
GO
USE [Events]
GO
/****** Object:  Table [dbo].[Command]    Script Date: 27/08/2022 09:45:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Command](
	[ExpectedVersion] [int] NULL,
	[CommandId] [uniqueidentifier] NOT NULL,
	[AggregateId] [uniqueidentifier] NOT NULL,
	[CausationId] [uniqueidentifier] NOT NULL,
	[CorrelationId] [uniqueidentifier] NOT NULL,
	[CommandPayload] [nvarchar](max) NOT NULL,
	[PayloadType] [nvarchar](1024) NOT NULL,
	[ProcessId] [uniqueidentifier] NULL,
	[QueueName] [nvarchar](1024) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Event]    Script Date: 27/08/2022 09:45:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Event](
	[Id] [int] NOT NULL,
	[EventId] [uniqueidentifier] NOT NULL,
	[AggregateId] [uniqueidentifier] NOT NULL,
	[CausationId] [uniqueidentifier] NOT NULL,
	[CorrelationId] [uniqueidentifier] NOT NULL,
	[ProcessId] [uniqueidentifier] NULL,
	[EventPayload] [nvarchar](max) NOT NULL,
	[PayloadType] [nvarchar](1024) NOT NULL,
	[Category] [nvarchar](1024) NOT NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Events] SET  READ_WRITE 
GO
