USE [master]
GO
/****** Object:  Database [Catalog]    Script Date: 27/08/2022 09:43:40 ******/
CREATE DATABASE [Catalog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Catalog', FILENAME = N'/var/opt/mssql/data/Catalog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Catalog_log', FILENAME = N'/var/opt/mssql/data/Catalog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 
ALTER DATABASE [Catalog] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))

ALTER DATABASE [Catalog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Catalog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Catalog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Catalog] SET ARITHABORT OFF 
GO
ALTER DATABASE [Catalog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Catalog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Catalog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Catalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Catalog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Catalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Catalog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Catalog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Catalog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Catalog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Catalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Catalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Catalog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Catalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Catalog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Catalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Catalog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Catalog] SET RECOVERY FULL 
GO
ALTER DATABASE [Catalog] SET  MULTI_USER 
GO
ALTER DATABASE [Catalog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Catalog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Catalog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Catalog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Catalog] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Catalog', N'ON'
GO
ALTER DATABASE [Catalog] SET QUERY_STORE = OFF
GO
USE [Catalog]
GO
/****** Object:  Table [dbo].[Catalog]    Script Date: 27/08/2022 09:43:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Catalog](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Price] [decimal](20, 4) NOT NULL,
	[PictureFileName] [nvarchar](1024) NULL,
	[PictureUri] [nvarchar](2024) NULL,
	[LastEventNumber] [int] NOT NULL,
	[Description] [nvarchar](512) NOT NULL,
	[CatalogTypeId] [uniqueidentifier] NOT NULL,
	[CatalogBrandId] [uniqueidentifier] NOT NULL,
	[OnReorder] [bit] NOT NULL,
	[AvailableStock] [decimal](18, 2) NOT NULL,
	[RestockThreshold] [decimal](18, 2) NOT NULL,
	[MaxStockThreshold] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Catalog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CatalogBrand]    Script Date: 27/08/2022 09:43:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CatalogBrand](
	[Id] [uniqueidentifier] NOT NULL,
	[Brand] [nvarchar](100) NOT NULL,
	[LastEventNumber] [int] NOT NULL,
 CONSTRAINT [PK_CatalogBrand] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CatalogType]    Script Date: 27/08/2022 09:43:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CatalogType](
	[Id] [uniqueidentifier] NOT NULL,
	[Type] [nvarchar](100) NOT NULL,
	[LastEventNumber] [int] NOT NULL,
 CONSTRAINT [PK_CatalogType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Catalog]  WITH CHECK ADD  CONSTRAINT [FK_CatalogBrandId] FOREIGN KEY([CatalogBrandId])
REFERENCES [dbo].[CatalogBrand] ([Id])
GO
ALTER TABLE [dbo].[Catalog] CHECK CONSTRAINT [FK_CatalogBrandId]
GO
ALTER TABLE [dbo].[Catalog]  WITH CHECK ADD  CONSTRAINT [FK_CatalogTypeId] FOREIGN KEY([CatalogTypeId])
REFERENCES [dbo].[CatalogType] ([Id])
GO
ALTER TABLE [dbo].[Catalog] CHECK CONSTRAINT [FK_CatalogTypeId]
GO
USE [master]
GO
ALTER DATABASE [Catalog] SET  READ_WRITE 
GO
